= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v1.2.0...v1.2.1++[1.2.1^] (2021-04-26)

=== Bug Fixes

* *zone.xml:* fix jinja error in rule.reject
(https://github.com/saltstack-formulas/firewalld-formula/commit/194cb99f1684bfd0a3ecdf89adc2acd1287d83dd[194cb99^])
* *zone.xml:* fix XML error
(https://github.com/saltstack-formulas/firewalld-formula/commit/88f9fd4687ebb0845123cadb9974419cf496a1bf[88f9fd4^])

=== Continuous Integration

* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/a2bcd11c4ca18bb374cc802c3575b791713b7a04[a2bcd11^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/98f91c29dff006757b18b3567789ed67435d012a[98f91c2^])
* *kitchen+gitlab:* adjust matrix to add `3003` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/79eb50a11aeb630f2732e8e1c1a29c054cb8ed4c[79eb50a^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/0bb7751957ed1d70cab6a711f9f0bc7b8ce54e3a[0bb7751^])

=== Tests

* *_mapdata:* add verification file for `fedora-34` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/b8e0cb8b14367dc22a8c776c4f3255bab674e9a7[b8e0cb8^])
* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/291adbd997657f3e34124c887a201c1b99d0a914[291adbd^])
* *_mapdata:* add verification files for new platforms
(https://github.com/saltstack-formulas/firewalld-formula/commit/b9d8775937bc9e533f0e47b384acefce41b80369[b9d8775^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v1.1.2...v1.2.0++[1.2.0^] (2021-02-05)

=== Continuous Integration

* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/a649d8763c92b25a4e1644caf37af4aabb688e03[a649d87^])

=== Features

* *pillar.example,test/:* add example and test for richrule ratelimit
(https://github.com/saltstack-formulas/firewalld-formula/commit/f25852637a7aeb8608b4618b952407b59b0dbf7e[f258526^])
* *zone.xml:* allow to rate limit 'accept' in rich rules
(https://github.com/saltstack-formulas/firewalld-formula/commit/a2f4f3b36e3295311128673f33f90c93de24288d[a2f4f3b^])

=== Tests

* *share:* standardise with latest changes [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/7df88b9e893f93be1b24de77338fdee0c1c8727c[7df88b9^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v1.1.1...v1.1.2++[1.1.2^] (2021-01-14)

=== Bug Fixes

* *_mapdata:* ensure map data is directly under `values`
(https://github.com/saltstack-formulas/firewalld-formula/commit/a29e81bac6febaf89859972a08c11cf6bda67a3f[a29e81b^])

=== Tests

* *_mapdata:* update for `_mapdata/init.sls` change
(https://github.com/saltstack-formulas/firewalld-formula/commit/a647d6d9a3d703e113d4e5eab480d43e9b0322c8[a647d6d^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v1.1.0...v1.1.1++[1.1.1^] (2020-12-27)

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/a615af103e7a9d89b05e8e7a4f9d139ec112c599[a615af1^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/472a16c283f60f84acc25846ef03da346c0a2cc5[472a16c^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/firewalld-formula/commit/a88d749499a613299dcb688f97aad9af97221ec6[a88d749^])

=== Tests

* *_mapdata:* generate verification files
(https://github.com/saltstack-formulas/firewalld-formula/commit/7665d77f67749722d5b3d8ef73aa75ede034d365[7665d77^])
* *map:* verify `map.jinja` dump using `_mapdata` state
(https://github.com/saltstack-formulas/firewalld-formula/commit/22869e0c7fa5ae6c7f8d354d4302cb945202347a[22869e0^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v1.0.0...v1.1.0++[1.1.0^] (2020-10-24)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/7a964e4738f0d7e3745da3b1f97a3407ca134381[7a964e4^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/a33cd641e248d0640dce3719836f5d4a0ff739e8[a33cd64^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/24e115cacb52e4a8a51fd92465e4442d6a68d1d3[24e115c^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/92540273969100880c55ad041c2e450deefef101[9254027^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/c7e4dee62a9a9a8f57cacde4b7d5c23ab9d36156[c7e4dee^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/118eacff459289ae21fd5cd630857b306f817ce9[118eacf^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/b6c60b27b9b37ab73a859bfac31f64df84046641[b6c60b2^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/93853b643f23e77f00a642d8f12b3da8b322ee8b[93853b6^])

=== Features

* *firewalld.conf:* support configuration of `AllowZoneDrifting`
(https://github.com/saltstack-formulas/firewalld-formula/commit/0ff53ffb2790ab95b71d3df461a04bca8f02a520[0ff53ff^]),
closes
https://github.com/saltstack-formulas/firewalld-formula/issues/44[#44^]

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.10.1...v1.0.0++[1.0.0^] (2020-04-18)

=== Bug Fixes

* do not error on unknown os_family grain
(https://github.com/saltstack-formulas/firewalld-formula/commit/94d2b0b97c242174c6f1c08cb2da2d2d03d98bd4[94d2b0b^])

=== Code Refactoring

* split default maps into separate files
(https://github.com/saltstack-formulas/firewalld-formula/commit/afcf5e770085565b11c25e9af522b194bd67fc30[afcf5e7^])

=== Tests

* *yaml_dump_spec:* update after splitting `map.jinja`
(https://github.com/saltstack-formulas/firewalld-formula/commit/d1f7a3717184bc22fde6e04d8672fcce0a462c4b[d1f7a37^])

=== BREAKING CHANGES

* `map.jinja` has been upgraded from using `pillar.get` to `config.get`.

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.10.0...v0.10.1++[0.10.1^] (2020-04-18)

=== Tests

* verify map output using `yaml_dump`
(https://github.com/saltstack-formulas/firewalld-formula/commit/69df9a62d6e12377b9a516e7454e75b49b0bffae[69df9a6^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.9.0...v0.10.0++[0.10.0^] (2020-04-02)

=== Bug Fixes

* *zone.xml:* adjust whitespacing to pass tests & macro at top of file
(https://github.com/saltstack-formulas/firewalld-formula/commit/d8f0f47a5408bde763050c457269ef129a48b050[d8f0f47^])

=== Features

* allow rich_rules to be specified as a dict
(https://github.com/saltstack-formulas/firewalld-formula/commit/cd4cec008983943213ac3bb721ab69c3a5214c54[cd4cec0^])

=== Styles

* *zone.xml:* remove all trailing whitespaces
(https://github.com/saltstack-formulas/firewalld-formula/commit/204efe5fc7065a2c2f4f55aa0138bf98675cba4e[204efe5^])

=== Tests

* *zones_spec:* check content of rendered zone files
(https://github.com/saltstack-formulas/firewalld-formula/commit/6ebfc6f20cfd72c2785514ab35484c9575401648[6ebfc6f^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.8.0...v0.9.0++[0.9.0^] (2020-02-12)

=== Features

* *zone.xml:* allow more services definition inside zone
(https://github.com/saltstack-formulas/firewalld-formula/commit/8d0172f5c7e0e1a2856dbbc0bf149ee8ddfd225a[8d0172f^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.7.0...v0.8.0++[0.8.0^] (2020-02-12)

=== Continuous Integration

* workaround issues with newly introduced `amazonlinux-1` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/ace343353d2c7b183b424e8a3f08b575417add3f[ace3433^])
* workaround issues with newly introduced `amazonlinux-1` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/b5a95f35ab98b872be852597d046d8d25f06b08b[b5a95f3^])
* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/908f5df86cd69f28ef4e48fbde13c35eb003b627[908f5df^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/0b82e43a1507bb748adefd13a0412ef7ccae8eb7[0b82e43^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/6e1b876298c2d782b132c1571d1f20564fb01bf1[6e1b876^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/70dc9aa3b4e299b6f8553132cd9d4401f4635f97[70dc9aa^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/97afbb157557ec3096cc8a8de48f737960dfda4e[97afbb1^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/d8bede7082130445461f990346f64d4db22e4bd2[d8bede7^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/b96cc569fe9a68deb2eb78974c216eb736d3b57b[b96cc56^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/firewalld-formula/commit/07e79001cddc4918f6ace716b15cf0658e09d374[07e7900^])

=== Features

* standardize license and hand over to saltstack formulas
(https://github.com/saltstack-formulas/firewalld-formula/commit/20cb8a60d362a7484892fc6703de954c67fb8763[20cb8a6^])

== link:++https://github.com/saltstack-formulas/firewalld-formula/compare/v0.6.2...v0.7.0++[0.7.0^] (2019-11-09)

=== Bug Fixes

* *map.jinja:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/firewalld-formula/commit/de4e1915fb17b2278132076c7946539191f1e018[de4e191^])
* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/firewalld-formula/commit/8136b75fa0266dc8d849a40a1fdb77129d6da31f[8136b75^])
* *yamllint:* fix all errors
(https://github.com/saltstack-formulas/firewalld-formula/commit/0f808d6afb383c56abfa439fde0fab46374ea2d7[0f808d6^])

=== Documentation

* *readme:* modify according to standard structure
(https://github.com/saltstack-formulas/firewalld-formula/commit/3df11fc75cade2d801183c3ae110821d2842f53f[3df11fc^])
* *readme:* move to `docs/` directory
(https://github.com/saltstack-formulas/firewalld-formula/commit/d47265f9743195a96565701e758789fbc14e3084[d47265f^])

=== Features

* *semantic-release:* implement for this formula
(https://github.com/saltstack-formulas/firewalld-formula/commit/c5f114d8863f6763c49cc08c723924649c8c1ed3[c5f114d^])
