= firewalld-formula

https://travis-ci.com/saltstack-formulas/firewalld-formula[image:https://travis-ci.com/saltstack-formulas/firewalld-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

A SaltStack Formula to set up and configure Firewalld, a dynamically
managed firewall with support for network/firewall zones to define the
trust level of network connections or interfaces.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

If you need (non-default) configuration, please pay attention to the
`pillar.example` file and/or link:#_special_notes[Special notes] section.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Special notes

None

== TODO

* configure local pre-commit hooks (code syntax check based on file
extension, check for ugly _utf-8 mac os white space_)

== Instructions

[arabic]
. Add this repository as a
http://docs.saltstack.com/topics/tutorials/gitfs.html[GitFS] backend in
your Salt master config.
. Configure your Pillar top file (`/srv/pillar/top.sls`), see
pillar.example
. Include this Formula within another Formula or simply define your
needed states within the Salt top file (`/srv/salt/top.sls`).

== Additional resources

None

== Formula Dependencies

None

== Contributions

Contributions are always welcome. All development guidelines you have to
know are

* write clean code (proper YAML+Jinja syntax, no trailing whitespaces,
no empty lines with whitespaces, LF only)
* set sane default settings
* test your code
* update README.rst doc

== Salt Compatibility

Tested with:

* 2018.3.x (will probably work too with 2017.x.x)

== OS Compatibility

Tested with:

* CentOS 7
* Debian 9
* Ubuntu 18.04

== Available states

=== `firewalld`

Manage firewalld

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `firewalld` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
